---
title: "Extraction_Pilot_1"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
library(tidyverse)
library(jspsychread)
library(writexl)
library(dplyr)
```

Extraction of participants from jatos file

```{r}
#Extract free experiment data

#Break down single file into multiple single participant files
fn <- ("cond3rd.txt")
text  <- readLines(fn)



#Loop through each part of the text file and write it to a separate text file
for(i in 1:length(text)) {
  
  part <- substring(text[i],
                    first=ifelse(i==1,1,1),
                    last=ifelse(i==25, nchar(text[i]), nchar(text[i])))
  
  
  
  #Write the i-th part to a separate text file
  #Paste0() function -> acts just like paste function but with a default separator, paste0('df',1:6) ->   "df1", "df2"...
  #Files are automatically saved in same directory as R document
  writeLines(part, paste0("part", i, ".txt"))

    
}


```

Extraction of condition 1 experiment

```{r}

#Number of participants
nSub <- length(text)
final_susp_overall<-data_frame()
final_sat_overall<-data_frame()
final_sat_overall_first_half<-data_frame()
final_sat_overall_second_half<-data_frame()
final_sat_overall_5_ratings<-data_frame()

#Create loop to read each particpant file previously extracted
for(iSub in 1:nSub) {
  partDirectory <-
    paste(
      "part",
      as.character(iSub),
      ".txt",
      sep = ""
    )
  
  #Read the data from each participant
  dataPerParticipant<- read_jspsych(partDirectory)
  
  #Get basic information per participant
  
  ratingSaving <-dataPerParticipant%>%
    filter(trial_type == trial_types$html_keyboard_response)%>%
    select(raw)%>%
    unnest_wider(raw)%>%
    filter(stimulus=='Press a key to continue')

  #Get the test game used for testing trials
  test_game <- ratingSaving[["test_game"]]
  
  #Rating game type selected
  rating_selected <- ratingSaving[["rating_selected"]]
  
  #Games in the group
  games <- sort(array(unname(unlist(ratingSaving[["group_selected"]]))))
  
  #Games in the group
  shuffled_games <- (array(unname(unlist(ratingSaving[["shuffled_games"]]))))
  
  
  #Get questionnaire results
  
  questionaireResults <-dataPerParticipant%>%
    filter(trial_type == trial_types$survey_multi_choice)%>%
    select(raw)%>%
    unnest_wider(raw)

 
  #Create a df for each participant
  questionaires <- paste0("questionaireResults_", iSub)

  #Assign partidipant name to df
  assign(questionaires, questionaireResults)
  
  #Save questionaire
  write_xlsx(questionaireResults, paste0("questionaireResults_", iSub, ".xlsx"))
  

  



  #Extract data for experiment reconstruction
  
  # Assign satisfactuon type rating (1 rating or 5 ratings) here for appropriate extraction:
  
  sat_type = '5_ratings'
  
  #If rating_selected = 0, extract suspense data, if suspense_rating = 1, extract satisfaction data
  
  ## ATTENTION, should be 0, but since i need to extract the satisfaction 5 ratings, that one was put as 0 instead.
  
  if (rating_selected == 1) {
    
    #Suspense rating extraction
  dataReconstruction_Susp <- dataPerParticipant %>%
    filter(trial_type == trial_types$html_slider_response) %>%
    select(raw) %>% #select column raw
    unnest_wider(raw)  %>%
    
    mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                           ifelse(game >= 6 & game <= 11, "losing",
                           ifelse(game >= 12 & game <= 17, "winning",
                           ifelse(game >= 18 & game <= 23, "losing",
                           ifelse(game >= 24 & game <= 29, "winning",
                           ifelse(game >= 30 & game <= 35, "losing", NA))))))) %>%
    
    mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                           ifelse(game >= 12 & game <= 23, "middle suspense",
                           ifelse(game >= 24 & game <= 35, "high suspense", NA)))) %>%
    mutate(response = scale(response))
  

  
  
    #Extract data for catch trials
  dataReconstruction_Susp_Overall <- dataPerParticipant %>%
    filter(trial_type == trial_types$html_button_response) %>%
    select(raw) %>% #select column raw
    unnest_wider(raw) %>%
    filter(test_part %in% c("catch_click_high") ) %>%
    mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                           ifelse(game >= 6 & game <= 11, "losing",
                           ifelse(game >= 12 & game <= 17, "winning",
                           ifelse(game >= 18 & game <= 23, "losing",
                           ifelse(game >= 24 & game <= 29, "winning",
                           ifelse(game >= 30 & game <= 35, "losing", NA)))))))  %>%
  
    mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                           ifelse(game >= 12 & game <= 23, "middle suspense",
                           ifelse(game >= 24 & game <= 35, "high suspense", NA))))

  
  
  #integrate suspense ratings to main data frame and remove first five test values as they are absent in real game
  #Z-score ratings at participant level
  dataReconstruction_Susp_Overall[["susp_rating"]] <- dataReconstruction_Susp$response[-(1:5)] 

  

  
  #Add participant number information
  dataReconstruction_Susp_Overall[["participant"]] <-  paste("Participant", iSub, sep = "")
  
  
     #Extract information on final count
dataReconstruction_End_Count <- dataPerParticipant %>%
  filter(trial_type %in% c(trial_types$html_keyboard_response, trial_types$html_button_response)) %>%  select(raw) %>% #select column raw
  unnest_wider(raw) %>%
  filter(test_part %in% c("final_count_test", "final_count", "catch_count") )
  
  
  #Replace the count column from dataReconstruction_Click with the one from end_count to also include the final count, remove first five test-values

dataReconstruction_Susp_Overall$count<- dataReconstruction_End_Count$count_end_of_trial[-(1:5)]



#Add last modifications to the format of dataReconstruction_Click to make more readable

dataReconstruction_Susp_Overall <- dataReconstruction_Susp_Overall %>%
  relocate (susp_rating, .after = test_part) %>%
  rename(catch_response = response) %>%
  rename(expected_outcome = outcome) %>%
  rename(real_outcome = result) %>%
  relocate(expected_outcome, .after = real_outcome)
  

  #Unlist columns to fix format
 
  #Create a df for each participant
  partNameSusp <- paste0("dfParticipant_Susp_", iSub)
  
  #Assign participant name to df and keep df_copy to append to final cross-participants df
  df_copy <- assign(partNameSusp, dataReconstruction_Susp_Overall)
  

  # Write appropriate columns of the data frame to an Excel file
  
  #Need to split pair values in two different cells
  #Create two new columns card_1 and card_2 in df_copy
  df_copy$card_1 <- NA
  df_copy$card_2 <- NA
  
  #Assign odd indexes of unlisted(df_copy$pair) to card_1, and even to card_2
  odd_indexes <- seq(from = 1, to = length(unlist(df_copy$pair)), by = 2)
  even_indexes <- seq(from = 2, to = length(unlist(df_copy$pair)), by = 2)

  df_copy$card_1 <- unlist(df_copy$pair)[odd_indexes]
  df_copy$card_2 <- unlist(df_copy$pair)[even_indexes]
        
    
  #Select only columns important for Python analysis
  df_copy <- df_copy %>%
    select("rt", "catch_response", "susp_rating", "trial", "game", "pair_number", "count", "expected_outcome", "suspense_level", "participant", "card_1", "card_2") %>%
    relocate("card_1" , "card_2", .after = pair_number)
  
#Append to final dataframe each participant
  final_susp_overall <- rbind(final_susp_overall,df_copy)
  
  write_xlsx(df_copy, paste0("dfParticipant_Susp_", iSub, ".xlsx"))
  
  

    
  } else if (rating_selected == 0) {
    
      if (sat_type == '1_rating') {
      
      
      #Satisfaction rating extraction
    dataReconstruction_Sat <- dataPerParticipant %>%
      filter(trial_type == trial_types$html_slider_response) %>%
      select(raw) %>% #select column raw
      unnest_wider(raw)  %>%
      mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                             ifelse(game >= 12 & game <= 23, "middle suspense",
                             ifelse(game >= 24 & game <= 35, "high suspense", NA)))) %>%
  
      mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                             ifelse(game >= 6 & game <= 11, "losing",
                             ifelse(game >= 12 & game <= 17, "winning",
                             ifelse(game >= 18 & game <= 23, "losing",
                             ifelse(game >= 24 & game <= 29, "winning",
                             ifelse(game >= 30 & game <= 35, "losing", NA)))))))
    
    #Remove first entry as it is the test games
    dataReconstruction_Sat <- slice(dataReconstruction_Sat, -(1:1)) %>%
      mutate(response = scale(response))
  
    
    
     #Extract data for catch trials and use this as a base to create the overall data frame with all centralised info
    dataReconstruction_Sat_Overall <- dataPerParticipant %>%
      filter(trial_type == trial_types$html_button_response) %>%
      select(raw) %>% #select column raw
      unnest_wider(raw) %>%
      mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                             ifelse(game >= 12 & game <= 23, "middle suspense",
                             ifelse(game >= 24 & game <= 35, "high suspense", NA)))) %>%
  
      mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                             ifelse(game >= 6 & game <= 11, "losing",
                             ifelse(game >= 12 & game <= 17, "winning",
                             ifelse(game >= 18 & game <= 23, "losing",
                             ifelse(game >= 24 & game <= 29, "winning",
                             ifelse(game >= 30 & game <= 35, "losing", NA))))))) %>%
    filter(test_part %in% c('catch_click_high_test', 'catch_click_high'))
    
    #Slice first five rows of data frame to remove test games
    dataReconstruction_Sat_Overall<-slice(dataReconstruction_Sat_Overall, -(1:5))
    
    
  #Merge satisfaction ratings in the main dataframe, but since there is only one satisfaction rating per game, interleave it with NA values
    
  # Create a vector of NA values with the desired length
  interleaved_values <- rep(NA, length(dataReconstruction_Sat$response) * 5)
  
  # Replace every fourth element with the values from dataReconstruction_Sat$response
  interleaved_values[seq(5, length(interleaved_values), by = 5)] <- dataReconstruction_Sat$response
  
  # Add new column to overall df to show satsifaction ratings
  dataReconstruction_Sat_Overall[["sat_rating"]] <- interleaved_values
  
  #Add participant number information
  dataReconstruction_Sat_Overall[["participant"]] <-  paste("Participant", iSub, sep = "")
  
    
    #Extract information on final count
  dataReconstruction_End_Count <- dataPerParticipant %>%
    filter(trial_type %in% c(trial_types$html_keyboard_response, trial_types$html_button_response)) %>%
    select(raw) %>% #select column raw
    unnest_wider(raw) %>%
    filter(test_part %in% c("final_count_test", "final_count", "catch_count") )
  
  
  
   #Create a df for each participant
    count <- paste0("count", iSub)
    
    #Assign partidipant name to df
    assign(count, dataReconstruction_End_Count)
    
    #Replace the count column from dataReconstruction_Sat_Overall with the one from end_count to also include the final count
  
  dataReconstruction_Sat_Overall$count<- dataReconstruction_End_Count$count_end_of_trial[-(1:5)]
  dataReconstruction_Sat_Overall$catch_count<- dataReconstruction_End_Count$catch_count[-(1:5)]
  dataReconstruction_Sat_Overall$catch_count_response<- dataReconstruction_End_Count$response[-(1:5)]
  
  
  
  #Add last modifications to the format of dataReconstruction_Sat_Overall to make more readable
  
  dataReconstruction_Sat_Overall <- dataReconstruction_Sat_Overall %>%
    relocate (sat_rating, .after = test_part) %>%
    rename(catch_response = response) %>%
    rename(expected_outcome = outcome) %>%
    rename(real_outcome = result) %>%
    relocate(expected_outcome, .after = real_outcome) %>%
    relocate(catch_count, .after = count) %>%
    relocate(catch_count_response, .after = catch_count)
  
  
  
  
  
  nData <- nrow(dataReconstruction_Sat_Overall)
    
    #Unlist columns to fix format
   
    #Create a df for each participant
    partNameSat <- paste0("dfParticipant_Sat_", iSub)
    
    #Assign participant name to df and keep df_copy to append to final cross-participants df
    df_copy<-assign(partNameSat, dataReconstruction_Sat_Overall)
  
  
    # Write appropriate columns of the data frame to an Excel file
    
    #Need to split pair values in two different cells
    #Create two new columns card_1 and card_2 in df_copy
    df_copy$card_1 <- NA
    df_copy$card_2 <- NA
    
    #Assign odd indexes of unlisted(df_copy$pair) to card_1, and even to card_2
    odd_indexes <- seq(from = 1, to = length(unlist(df_copy$pair)), by = 2)
    even_indexes <- seq(from = 2, to = length(unlist(df_copy$pair)), by = 2)
  
    df_copy$card_1 <- unlist(df_copy$pair)[odd_indexes]
    df_copy$card_2 <- unlist(df_copy$pair)[even_indexes]
    
  
          
      
    #Select only columns important for Python analysis
    df_copy <- df_copy %>%
      select("rt", "catch_response", "sat_rating", "trial", "game", "pair_number", "count", "catch_count", "catch_count_response", "expected_outcome", "suspense_level", "participant", "card_1", "card_2") %>%
      relocate("card_1" , "card_2", .after = pair_number)
  
    
    #extract the data split in 2 to see if there is a behaviour change throughout the experiment
    df_copy_first_half <-slice(df_copy, 1:45)
    df_copy_second_half <-slice(df_copy, 46:90)
    
  #Append to final dataframe each participant
    final_sat_overall <- rbind(final_sat_overall,df_copy)
    
    
    final_sat_overall_first_half <- rbind(final_sat_overall_first_half,df_copy_first_half)
    final_sat_overall_second_half <- rbind(final_sat_overall_second_half,df_copy_second_half)
    
    
    #Replace all NULL values with a NA in catch_count_response to facilitate extraction
    #Unlist the list colunmn for the extraction
    final_sat_overall$catch_count_response <- lapply(final_sat_overall$catch_count_response, function(x) if (is.null(x)) NA else x)
    final_sat_overall$catch_count_response<-unlist(final_sat_overall$catch_count_response)
    
      #Replace all NULL values with a NA in catch_count_response to facilitate extraction
    #Unlist the list colunmn for the extraction
    final_sat_overall_first_half$catch_count_response <- lapply(final_sat_overall_first_half$catch_count_response, function(x) if (is.null(x)) NA else x)
    final_sat_overall_first_half$catch_count_response<-unlist(final_sat_overall_first_half$catch_count_response)
    
    
       #Replace all NULL values with a NA in catch_count_response to facilitate extraction
    #Unlist the list colunmn for the extraction
    final_sat_overall_second_half$catch_count_response <- lapply(final_sat_overall_second_half$catch_count_response, function(x) if (is.null(x)) NA else x)
    final_sat_overall_second_half$catch_count_response<-unlist(final_sat_overall_second_half$catch_count_response)
  
  
  
    #save participant data frame
    write_xlsx(df_copy, paste0("dfParticipant_Sat_", iSub, ".xlsx"))
    write_xlsx(df_copy_first_half, paste0("dfParticipant_Sat_First_Half", iSub, ".xlsx"))
    write_xlsx(df_copy_second_half, paste0("dfParticipant_Sat_Second_Half", iSub, ".xlsx"))
  
    #save questionnaire results
    write_xlsx(questionaireResults, paste0("dfQuestionaire_Sat_Participant", iSub, ".xlsx"))
    
      
      }
    
  
  
    else if (sat_type == '5_ratings') {
      
      
      
       #Satisfaction 5 ratings rating extraction
    dataReconstruction_Sat_5_ratings <- dataPerParticipant %>%
      filter(trial_type == trial_types$html_slider_response) %>%
      select(raw) %>% #select column raw
      unnest_wider(raw)  %>%
      
      mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                             ifelse(game >= 6 & game <= 11, "losing",
                             ifelse(game >= 12 & game <= 17, "winning",
                             ifelse(game >= 18 & game <= 23, "losing",
                             ifelse(game >= 24 & game <= 29, "winning",
                             ifelse(game >= 30 & game <= 35, "losing", NA))))))) %>%
      
      mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                             ifelse(game >= 12 & game <= 23, "middle suspense",
                             ifelse(game >= 24 & game <= 35, "high suspense", NA)))) %>%
      mutate(response = scale(response))
    
  
    
    
      #Extract data for catch trials
    dataReconstruction_Sat_Overall_5_ratings <- dataPerParticipant %>%
      filter(trial_type == trial_types$html_button_response) %>%
      select(raw) %>% #select column raw
      unnest_wider(raw) %>%
      filter(test_part %in% c("catch_click_high") ) %>%
      mutate(outcome = ifelse(game >= 0 & game <= 5, "winning",
                             ifelse(game >= 6 & game <= 11, "losing",
                             ifelse(game >= 12 & game <= 17, "winning",
                             ifelse(game >= 18 & game <= 23, "losing",
                             ifelse(game >= 24 & game <= 29, "winning",
                             ifelse(game >= 30 & game <= 35, "losing", NA)))))))  %>%
    
      mutate(suspense_level = ifelse(game >= 0 & game <= 11, "low suspense",
                             ifelse(game >= 12 & game <= 23, "middle suspense",
                             ifelse(game >= 24 & game <= 35, "high suspense", NA))))
  
    
    
    # Add an empty row every 6th rating in dataReconstruction_Sat_Overall_5_ratings to give space for the last rating per round
    
    
    # Create an empty row with the same column names
  new_row <- as.data.frame(matrix(NA, nrow = 1, ncol = ncol(dataReconstruction_Sat_Overall_5_ratings)))
  colnames(new_row) <- colnames(dataReconstruction_Sat_Overall_5_ratings)  # Assign correct column names
  
  # Define positions where new rows should be inserted
  insert_positions <- seq(5, nrow(dataReconstruction_Sat_Overall_5_ratings), by = 5)
  
  # Function to insert a row after every 6th row
  insert_every_nth <- function(df, new_row, positions) {
    new_df <- bind_rows(
      lapply(seq_len(nrow(df)), function(i) {
        if (i %in% positions) {
          rbind(df[i, ], new_row)  # Insert new row after the 6th, 12th, etc.
        } else {
          df[i, , drop = FALSE]  # Ensure it stays as a dataframe
        }
      })
    )
    return(new_df)
  }
  
  # Apply the function to insert the new row
  dataReconstruction_Sat_Overall_5_ratings <- insert_every_nth(dataReconstruction_Sat_Overall_5_ratings, new_row, insert_positions)
  
    
    #integrate suspense ratings to main data frame and remove first six test values as they are absent in real game
    #Z-score ratings at participant level
    dataReconstruction_Sat_Overall_5_ratings[["sat_rating"]] <- dataReconstruction_Sat_5_ratings$response[-(1:6)] 
  
    
  
    
    #Add participant number information
    dataReconstruction_Sat_Overall_5_ratings[["participant"]] <-  paste("Participant", iSub, sep = "")
    
  
    
     #Extract information on final count
  dataReconstruction_End_Count <- dataPerParticipant %>%
    filter(trial_type %in% c(trial_types$html_keyboard_response, trial_types$html_button_response)) %>%
    select(raw) %>% #select column raw
    unnest_wider(raw) %>%
    filter(test_part %in% c("final_count_test", "final_count", "catch_count") )
  
  
  
  new_row <- as.data.frame(matrix(NA, nrow = 1, ncol = ncol(dataReconstruction_End_Count)))
  insert_positions <- seq(5, nrow(dataReconstruction_End_Count), by = 5)
  colnames(new_row) <- colnames(dataReconstruction_End_Count)  # Assign correct column names
  dataReconstruction_End_Count <- insert_every_nth(dataReconstruction_End_Count, new_row, insert_positions)
  
    
  
   #Create a df for each participant
    count <- paste0("count", iSub)
    
    #Assign partidipant name to df
    assign(count, dataReconstruction_End_Count)
    
    #Replace the count column from dataReconstruction_Sat_Overall with the one from end_count to also include the final count
  
  dataReconstruction_Sat_Overall_5_ratings$count<- dataReconstruction_End_Count$count_end_of_trial[-(1:6)]
  dataReconstruction_Sat_Overall_5_ratings$catch_count<- dataReconstruction_End_Count$catch_count[-(1:6)]
  dataReconstruction_Sat_Overall_5_ratings$catch_count_response<- dataReconstruction_End_Count$response[-(1:6)]
  
  
  
  
  
  #Add last modifications to the format of dataReconstruction_Sat_Overall to make more readable
  
  dataReconstruction_Sat_Overall_5_ratings <- dataReconstruction_Sat_Overall_5_ratings %>%
    relocate (sat_rating, .after = test_part) %>%
    rename(sat_rating_5_ratings = sat_rating) %>%
    rename(catch_response = response) %>%
    rename(expected_outcome = outcome) %>%
    rename(real_outcome = result) %>%
    relocate(expected_outcome, .after = real_outcome) %>%
    #relocate(catch_count, .after = count) %>%
    relocate(catch_count_response, .after = expected_outcome)  

    
  
    #Unlist columns to fix format
   
    #Create a df for each participant
    partNameSusp <- paste0("dfParticipant_Sat_5_ratings", iSub)
    
    #Assign participant name to df and keep df_copy to append to final cross-participants df
    df_copy <- assign(partNameSusp, dataReconstruction_Sat_Overall_5_ratings)
    
  
    # Write appropriate columns of the data frame to an Excel file
    
    #Need to split pair values in two different cells
    #Create two new columns card_1 and card_2 in df_copy
    df_copy$card_1 <- NA
    df_copy$card_2 <- NA
    
    #Assign odd indexes of unlisted(df_copy$pair) to card_1, and even to card_2
    # Ensure NA values are not removed when unlisting
    pair_unlisted <- unlist(df_copy$pair)
    # Remove NA values from the vector
    pair_unlisted <- na.omit(pair_unlisted)
    
    
   
    # Assign odd and even indexes, considering NA values
    odd_indexes <- seq(from = 1, by = 2, length.out = 90)

    even_indexes <- seq(from = 0, by = 2, length.out = 91)
    
    card_1 <- pair_unlisted[odd_indexes]
    card_2 <- pair_unlisted[even_indexes]
    
    
    # Function to insert NA every 5th element
insert_na_every_5th <- function(vec) {
  n <- length(vec)
  indices <- seq(6, n + floor(n / 5), by = 6)  # Compute NA insertion positions
  
  new_vec <- rep(NA, length(vec) + length(indices))  # Placeholder vector
  new_vec[-indices] <- vec  # Fill in original values
  
  return(new_vec)
}

    
  # Insert NA every 5th element
card_1_with_na <- insert_na_every_5th(card_1)
card_2_with_na <- insert_na_every_5th(card_2)

# Print the modified vectors
print(card_1_with_na)
print(card_2_with_na)
    
    # Assign values while keeping NA values
    df_copy$card_1 <- card_1_with_na
    df_copy$card_2 <-card_2_with_na
    
      
    #Select only columns important for Python analysis
    df_copy <- df_copy %>%
      select("rt", "catch_response", "sat_rating_5_ratings", "trial", "game", "pair_number", "count", "expected_outcome", "suspense_level", "participant", "card_1", "card_2") %>%
      relocate("card_1" , "card_2", .after = pair_number)
    
  #Append to final dataframe each participant
    final_sat_overall_5_ratings <- rbind(final_sat_overall_5_ratings,df_copy)
    
    write_xlsx(df_copy, paste0("dfParticipant_Sat_5_ratings", iSub, ".xlsx"))
    
      
    }
    
  }
  
}
```



```{r}
#Save dataframes

if (rating_selected == 1) {
  
  # Suspense
  write_xlsx(final_susp_overall, "final_Susp_Overall_2.xlsx")

} else if (rating_selected == 0) {

  # Satisfaction
  if (sat_type == "5_ratings") {
    write_xlsx(final_sat_overall_5_ratings, "final_Sat_Overall_5_ratings_3rd.xlsx")
  } else {
    write_xlsx(final_sat_overall, "final_Sat_Overall.xlsx")
    # write_xlsx(final_sat_overall_first_half, "final_Sat_Overall_First_Half.xlsx")
    # write_xlsx(final_sat_overall_second_half, "final_Sat_Overall_Second_Half.xlsx")
  }

}


```






